name: Feature Request
description: Propose a new feature or improvement
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        **Read [CONTRIBUTING.md](../../CONTRIBUTING.md) before submitting.** Open an issue _before_ writing any code.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the gap or friction you're experiencing.
      placeholder: 'e.g. I have 5 wallets on Cosmos and have to import them one at a time. Batch import would save time.'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought about, and why you prefer this one.

  - type: checkboxes
    id: willing_to_contribute
    attributes:
      label: Contribution
      options:
        - label: I am willing to implement this myself (after the issue is acknowledged)
