import { parseDecimal, type Currency } from '@exitbook/foundation';

import type { CostBasisWorkflowResult } from '../../workflow/workflow-result-types.js';

export function createStandardWorkflowArtifact(
  overrides?: Partial<Extract<CostBasisWorkflowResult, { kind: 'standard-workflow' }>>
): Extract<CostBasisWorkflowResult, { kind: 'standard-workflow' }> {
  const calculationId = 'df94bdd2-b8ee-4486-9c83-b0f91ca62514';

  return {
    kind: 'standard-workflow',
    summary: {
      calculation: {
        id: calculationId,
        calculationDate: new Date('2026-03-15T12:00:00.000Z'),
        config: {
          method: 'fifo',
          currency: 'USD',
          jurisdiction: 'US',
          taxYear: 2024,
          startDate: new Date('2024-01-01T00:00:00.000Z'),
          endDate: new Date('2024-12-31T23:59:59.999Z'),
        },
        startDate: new Date('2024-01-01T00:00:00.000Z'),
        endDate: new Date('2024-12-31T23:59:59.999Z'),
        totalProceeds: parseDecimal('14925'),
        totalCostBasis: parseDecimal('16000'),
        totalGainLoss: parseDecimal('-1075'),
        totalTaxableGainLoss: parseDecimal('-30'),
        assetsProcessed: ['BTC'],
        transactionsProcessed: 5,
        lotsCreated: 2,
        disposalsProcessed: 2,
        status: 'completed',
        createdAt: new Date('2026-03-15T12:00:00.000Z'),
        completedAt: new Date('2026-03-15T12:00:00.000Z'),
      },
      lotsCreated: 2,
      disposalsProcessed: 2,
      totalCapitalGainLoss: parseDecimal('-1075'),
      totalTaxableGainLoss: parseDecimal('-30'),
      assetsProcessed: ['BTC'],
      lots: [],
      disposals: [],
      lotTransfers: [],
    },
    lots: [
      {
        id: 'lot-1',
        calculationId,
        acquisitionTransactionId: 1,
        assetId: 'exchange:kraken:btc',
        assetSymbol: 'BTC' as Currency,
        quantity: parseDecimal('1'),
        costBasisPerUnit: parseDecimal('10000'),
        totalCostBasis: parseDecimal('10000'),
        acquisitionDate: new Date('2023-01-05T00:00:00.000Z'),
        method: 'fifo',
        remainingQuantity: parseDecimal('0'),
        status: 'fully_disposed',
        createdAt: new Date('2026-03-15T12:00:00.000Z'),
        updatedAt: new Date('2026-03-15T12:00:00.000Z'),
      },
      {
        id: 'lot-2',
        calculationId,
        acquisitionTransactionId: 2,
        assetId: 'exchange:kraken:btc',
        assetSymbol: 'BTC' as Currency,
        quantity: parseDecimal('1'),
        costBasisPerUnit: parseDecimal('15000'),
        totalCostBasis: parseDecimal('15000'),
        acquisitionDate: new Date('2024-06-01T00:00:00.000Z'),
        method: 'fifo',
        remainingQuantity: parseDecimal('0.35'),
        status: 'partially_disposed',
        createdAt: new Date('2026-03-15T12:00:00.000Z'),
        updatedAt: new Date('2026-03-15T12:00:00.000Z'),
      },
    ],
    disposals: [
      {
        id: 'disp-1',
        lotId: 'lot-1',
        disposalTransactionId: 3,
        quantityDisposed: parseDecimal('1'),
        proceedsPerUnit: parseDecimal('9000'),
        totalProceeds: parseDecimal('8955'),
        grossProceeds: parseDecimal('9000'),
        sellingExpenses: parseDecimal('45'),
        netProceeds: parseDecimal('8955'),
        costBasisPerUnit: parseDecimal('10000'),
        totalCostBasis: parseDecimal('10000'),
        gainLoss: parseDecimal('-1045'),
        disposalDate: new Date('2024-11-01T00:00:00.000Z'),
        holdingPeriodDays: 666,
        lossDisallowed: true,
        disallowedLossAmount: parseDecimal('1045'),
        taxTreatmentCategory: 'long_term',
        createdAt: new Date('2026-03-15T12:00:00.000Z'),
      },
      {
        id: 'disp-2',
        lotId: 'lot-2',
        disposalTransactionId: 3,
        quantityDisposed: parseDecimal('0.4'),
        proceedsPerUnit: parseDecimal('15000'),
        totalProceeds: parseDecimal('5970'),
        grossProceeds: parseDecimal('6000'),
        sellingExpenses: parseDecimal('30'),
        netProceeds: parseDecimal('5970'),
        costBasisPerUnit: parseDecimal('15000'),
        totalCostBasis: parseDecimal('6000'),
        gainLoss: parseDecimal('-30'),
        disposalDate: new Date('2024-11-01T00:00:00.000Z'),
        holdingPeriodDays: 153,
        lossDisallowed: false,
        disallowedLossAmount: undefined,
        taxTreatmentCategory: 'short_term',
        createdAt: new Date('2026-03-15T12:00:00.000Z'),
      },
    ],
    lotTransfers: [
      {
        id: 'transfer-1',
        calculationId,
        sourceLotId: 'lot-2',
        provenance: {
          kind: 'confirmed-link',
          linkId: 11,
          sourceMovementFingerprint: 'movement:exchange:source:4:btc:outflow:0',
          targetMovementFingerprint: 'movement:blockchain:target:5:btc:inflow:0',
        },
        quantityTransferred: parseDecimal('0.25'),
        costBasisPerUnit: parseDecimal('15000'),
        sourceTransactionId: 4,
        targetTransactionId: 5,
        transferDate: new Date('2024-12-15T00:00:00.000Z'),
        metadata: {
          sameAssetFeeUsdValue: parseDecimal('12.50'),
        },
        createdAt: new Date('2026-03-15T12:00:00.000Z'),
      },
    ],
    executionMeta: {
      missingPricesCount: 0,
      retainedTransactionIds: [1, 2, 3, 4, 5],
    },
    ...overrides,
  };
}

export function createCanadaWorkflowArtifact(
  overrides?: Partial<Extract<CostBasisWorkflowResult, { kind: 'canada-workflow' }>>
): Extract<CostBasisWorkflowResult, { kind: 'canada-workflow' }> {
  return {
    kind: 'canada-workflow',
    calculation: {
      id: '0f93f130-e4d6-4d67-9458-84875b0f868a',
      calculationDate: new Date('2026-03-15T12:00:00.000Z'),
      method: 'average-cost',
      jurisdiction: 'CA',
      taxYear: 2024,
      displayCurrency: 'CAD' as Currency,
      taxCurrency: 'CAD',
      startDate: new Date('2024-01-01T00:00:00.000Z'),
      endDate: new Date('2024-12-31T23:59:59.999Z'),
      transactionsProcessed: 3,
      assetsProcessed: ['BTC'],
    },
    taxReport: {
      calculationId: '0f93f130-e4d6-4d67-9458-84875b0f868a',
      taxCurrency: 'CAD',
      acquisitions: [
        {
          id: 'layer-1',
          acquisitionEventId: 'acq-1',
          transactionId: 10,
          taxPropertyKey: 'BTC',
          assetSymbol: 'BTC' as Currency,
          acquiredAt: new Date('2024-01-10T00:00:00.000Z'),
          quantityAcquired: parseDecimal('1'),
          remainingQuantity: parseDecimal('0.4'),
          totalCostCad: parseDecimal('50000'),
          remainingAllocatedAcbCad: parseDecimal('20000'),
          costBasisPerUnitCad: parseDecimal('50000'),
        },
      ],
      dispositions: [
        {
          id: 'disp-1',
          dispositionEventId: 'disp-1',
          transactionId: 11,
          taxPropertyKey: 'BTC',
          assetSymbol: 'BTC' as Currency,
          disposedAt: new Date('2024-03-10T00:00:00.000Z'),
          quantityDisposed: parseDecimal('0.6'),
          proceedsCad: parseDecimal('36000'),
          costBasisCad: parseDecimal('30000'),
          gainLossCad: parseDecimal('6000'),
          deniedLossCad: parseDecimal('100'),
          taxableGainLossCad: parseDecimal('3050'),
          acbPerUnitCad: parseDecimal('50000'),
        },
      ],
      transfers: [
        {
          id: 'transfer-1',
          direction: 'internal',
          sourceTransferEventId: 'transfer-out-1',
          targetTransferEventId: 'transfer-in-1',
          sourceTransactionId: 11,
          targetTransactionId: 12,
          linkId: 9,
          transactionId: 11,
          taxPropertyKey: 'BTC',
          assetSymbol: 'BTC' as Currency,
          transferredAt: new Date('2024-03-10T00:00:00.000Z'),
          quantity: parseDecimal('0.2'),
          carriedAcbCad: parseDecimal('10000'),
          carriedAcbPerUnitCad: parseDecimal('50000'),
          feeAdjustmentCad: parseDecimal('25'),
        },
      ],
      superficialLossAdjustments: [
        {
          id: 'sla-1',
          adjustedAt: new Date('2024-03-15T00:00:00.000Z'),
          assetSymbol: 'BTC' as Currency,
          deniedLossCad: parseDecimal('100'),
          deniedQuantity: parseDecimal('0.1'),
          relatedDispositionId: 'disp-1',
          taxPropertyKey: 'BTC',
          substitutedPropertyAcquisitionId: 'layer-1',
        },
      ],
      summary: {
        totalProceedsCad: parseDecimal('36000'),
        totalCostBasisCad: parseDecimal('30000'),
        totalGainLossCad: parseDecimal('6000'),
        totalTaxableGainLossCad: parseDecimal('3050'),
        totalDeniedLossCad: parseDecimal('100'),
      },
      displayContext: {
        transferMarketValueCadByTransferId: new Map([['transfer-1', parseDecimal('12000')]]),
      },
    },
    inputContext: {
      taxCurrency: 'CAD',
      scopedTransactionIds: [10, 11, 12],
      validatedTransferLinkIds: [9],
      feeOnlyInternalCarryoverSourceTransactionIds: [],
      inputEvents: [],
    },
    executionMeta: {
      missingPricesCount: 0,
      retainedTransactionIds: [10, 11, 12],
    },
    ...overrides,
  };
}
